Common fixture code
ice-blockchain/wintr pull request #12
Opened 2022-07-07 09:15 UTC by antonh21

Most of the fixture code that is needed for services was moved to the wintr.

2022-07-07 09:31 UTC, nusanovkornilov-leftclick requested changes

2022-07-07 09:31 UTC, nusanovkornilov-leftclick commented on server/fixture/contract.go
> +		Body    string
Should be io.ReadCloser like wrapJSONBody return value to support multipart/form-data in the future ( we'll need it for modify user requests)

2022-07-07 09:31 UTC, nusanovkornilov-leftclick commented on server/fixture/fixture.go
> +	r, err := http.NewRequestWithContext(ctx, arg.Method, fmt.Sprintf("https://%v%v", tr.ServerAddr, arg.URL), wrapJSONBody(arg.Body))
call to wrapJSONBody should be somewhere outside of this func (we'll use not only json but multipart/form-data also)

2022-07-07 09:35 UTC, nusanovkornilov-leftclick commented on server/fixture/fixture.go
> +	r, err := http.NewRequestWithContext(ctx, arg.Method, fmt.Sprintf("https://%v%v", tr.ServerAddr, arg.URL), wrapJSONBody(arg.Body))
also, here is implermentation of body builder for multipart, looks like we can add it to this PR too:
`func wrapMultipartBody(tb testing.TB, values map[string]interface{}) (io.ReadCloser, string) {
	tb.Helper()
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	defer writer.Close()
	for fieldName, fieldValue := range values {
		switch v := fieldValue.(type) {
		case *os.File:
			formFile, err := writer.CreateFormFile(fieldName, v.Name())
			require.NoError(tb, err)
			_, err = io.Copy(formFile, v)
			require.NoError(tb, err)
		case string:
			require.NoError(tb, writer.WriteField(fieldName, v))
		}
	}

	return io.NopCloser(body), writer.FormDataContentType()
}`

2022-07-12 10:10 UTC, nusanovkornilov-leftclick commented on server/fixture/contract.go
> +	TestConnector interface {
It seems we also need a new method to access testdataPath to setup mount points properly

2022-07-12 10:12 UTC, victor-oancea-leftclick-io commented on server/fixture/contract.go
> +		WrapJSONBody(jsonData string) (ReqBody, ContentType)
Yep we do. The only public methods in the packages are to build stuff. In the stuff it builds you have everything that you need.

2022-07-12 10:12 UTC, victor-oancea-leftclick-io commented on server/fixture/contract.go
> +	TestConnector interface {
Hmmm, right

2022-07-12 13:32 UTC, victor-oancea-leftclick-io commented on connectors/storage/fixture/fixture.go
> +	tc.Connector = storage.MustConnect(ctx, func() {}, "", tc.applicationYamlKey)
local.go is not responsible for loading the ddl

and yea, you need `skipSchemaCreation`

2022-07-12 13:37 UTC, victor-oancea-leftclick-io commented on connectors/message_broker/fixture/fixture.go
> +	applicationYamlTestKey := fmt.Sprintf("%v_test", applicationYAMLKey)
not an issue. %v_test is meant for connectors, not setting up the containers. Everything related to docker/dockercompose can use %v, thats the production one.

%v_test is only required for clients

2022-07-12 13:37 UTC, victor-oancea-leftclick-io commented on connectors/fixture/fixture.go
> +	return &testRunner{
nope, check above

2022-07-12 13:42 UTC, victor-oancea-leftclick-io commented on connectors/storage/fixture/fixture.go
> +	tc.Connector = storage.MustConnect(ctx, func() {}, "", tc.applicationYamlKey)
yea, it should validate it, why is it empty on startup?

2022-07-12 13:50 UTC, nusanovkornilov-leftclick commented on connectors/storage/fixture/fixture.go
> +	tc.Connector = storage.MustConnect(ctx, func() {}, "", tc.applicationYamlKey)
because of DDL is initialized by the users package, when database container starts from tc.delegate.Setup(ctx) ( a couple of lines earlier) it does not contain DDL. And it is not passed to initialize on MustConnect call, so validation fails

2022-07-12 14:10 UTC, victor-oancea-leftclick-io commented on connectors/fixture/fixture.go
> +		tr.orderedConnectorCleanUps[order] = append(tr.orderedConnectorCleanUps[order], orderedConnectorCleanUp.cleanUp)
give me more details or fix it urself

2022-07-13 16:44 UTC, victor-oancea-leftclick-io approved these changes

2022-07-14 06:57 UTC, nusanovkornilov-leftclick approved these changes

2022-07-14 06:57 UTC, merged