email package
ice-blockchain/wintr pull request #13
Opened 2022-07-08 08:11 UTC by kfedor

2022-07-08 09:10 UTC, antonh21 requested changes

2022-07-08 09:10 UTC, antonh21 commented on email/email.go
> +			return errors.New(j.Errors[0].Message)
Why is the only the first error message returned?

2022-07-08 09:58 UTC, kfedor commented on email/email.go
> +	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
200-299 are positives

2022-07-08 10:00 UTC, kfedor commented on email/contract.go
> +	TextHTML  = "text/html"
This lib allows us to use rich formatting is different formats 
we can include messages like

contentHTML := email.Content{
	Type: TextHtml,
	Data: "<h1>TEXT Html!</h1>",
}

contentPlain := email.Content{
	Type: Plaintext,
	Data: "<h1>TEXT Html!</h1>",
}

and include all of them into one message
so this is for future client use

2022-07-08 10:01 UTC, kfedor commented on email/email.go
> +			return errors.New(j.Errors[0].Message)
I have no idea why sendgrid returns error as array
I didnt see many

2022-07-08 10:15 UTC, antonh21 commented on email/email.go
> +	var wg sync.WaitGroup
Why not to use errGroup here instead of waitGroup + error channel?

2022-07-08 10:16 UTC, antonh21 commented on email/contract.go
> +	TextHTML  = "text/html"
I see.
But I would rename constants at least to this variant:
```
ContentTypeTextHTML  = "text/html"
ContentTypeTextPlain = "text/plain"
ContentTypeMarkdown  = "text/markdown"
```

it it much easier to find them when you use wintr library, typing:
```
email.ContentType... // And it will show all available content types.
```

2022-07-08 10:21 UTC, kfedor commented on email/email.go
> +	var wg sync.WaitGroup
we collect all errors, not first
discussed this is sms before

2022-07-08 10:27 UTC, kfedor commented on email/contract.go
> +	TextHTML  = "text/html"
ok!

2022-07-11 07:34 UTC, antonh21 approved these changes

2022-07-11 09:25 UTC, nusanovkornilov-leftclick approved these changes

2022-07-11 10:28 UTC, victor-oancea-leftclick-io commented on email/email.go
> +		content := mail.NewContent(c.Type, c.Data)
This would be needed if we had some attachments, but we just have the body

2022-07-11 12:59 UTC, kfedor commented on email/contract.go
> +		To      Participant
this is why I send multiple messages
its possible to send single message with multuple tos, ccs, bcc but this doesnt suite us

2022-07-11 13:00 UTC, kfedor commented on email/email.go
> +		content := mail.NewContent(c.Type, c.Data)
no, this is for multi content, like we include two contents with text/plain & text/html and users client choose which if compatible. We cant add attach using mail.NewContent, there are mail.NewAttachment for this

2022-07-11 19:25 UTC, merged