inApp notifications
ice-blockchain/wintr pull request #14
Opened 2022-07-15 12:44 UTC by kfedor

2022-07-15 12:45 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +		Header   string
Whats this for?

2022-07-15 12:47 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
why 1?

2022-07-15 12:47 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +) error {
one line it

2022-07-15 12:48 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +	_, err := notify.AddActivity(ctx, i.makeActivity(notify.ID(), data))
handle response?

2022-07-15 12:48 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		activities[c] = i.makeActivity(notify.ID(), d)
can we add activities for multiple users? cuz otherwise this is useless

2022-07-15 12:50 UTC, kfedor commented on notifications/inapp/contract.go
> +		Header   string
this is single feed element
header image and body describes everything..

2022-07-15 12:50 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) Send(ctx context.Context, slug, userID string, data *NotificationData) error {
move the slug to the New constructor, and move userId inside notificationData

2022-07-15 12:52 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) SendMulti(ctx context.Context, slug, userID string, data []*NotificationData) error {
if its only for the same userID its useless, if you can't do it for multiple users, follow the same approach with goroutines that you did for the rest

2022-07-15 12:53 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
They didnt describe this field but its mandatory
Activity has its own unique id, so this is not ID
all samples shows "1" but value doesn't matter
there are a lot of strange things in their code :(

2022-07-15 12:53 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) Get(ctx context.Context, slug, userID string) ([]*NotificationData, error) {
GetAll

2022-07-15 12:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +	res := make([]*NotificationData, len(resp.Results))
make([]*NotificationData, 0, len(resp.Results))

2022-07-15 12:55 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +			Header:   resp.Results[c].Verb,
rename header to `action`

2022-07-15 12:55 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +			BodyText: resp.Results[c].Extra["bodyText"].(string),
just body, without text

2022-07-15 12:56 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Actor:  id,
from what I remember you had to have some sort of pattern here, right : I.E. `userId:123124325`

2022-07-15 13:03 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
you need to include it in notification data, and name it `Subject`

The notification feed is a list of activities, that have an actor, an action (verb) and a subject (which is the object).

I would transform actor & object into a
Reference struct {
 ID string
 Type string
}

2022-07-15 13:06 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
also, you should have a foreign_id or something similar in the API, we also need to set that from a field in notification data

2022-07-15 13:07 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
oh, and we need to add custom data as well

2022-07-15 13:09 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +	_, err := notify.AddActivity(ctx, i.makeActivity(notify.ID(), data))
ok
return some id ?

2022-07-15 13:10 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		activities[c] = i.makeActivity(notify.ID(), d)
yes, ok

2022-07-15 13:11 UTC, kfedor commented on notifications/inapp/inapp.go
> +func (i *inApp) Send(ctx context.Context, slug, userID string, data *NotificationData) error {
would we always use the same slug, like "users" ?

2022-07-15 13:12 UTC, kfedor commented on notifications/inapp/inapp.go
> +func (i *inApp) SendMulti(ctx context.Context, slug, userID string, data []*NotificationData) error {
Activity depends on ID which is slug:name so it can be done easily

2022-07-15 13:16 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) SendMulti(ctx context.Context, slug, userID string, data []*NotificationData) error {
what name?

2022-07-15 13:17 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
Custom data is hold in Extra just like body and imageUrl
it looks like we need to use predefined values or map[string]string
what to do?

2022-07-15 13:18 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +) error {
ok

2022-07-15 13:21 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +	_, err := notify.AddActivity(ctx, i.makeActivity(notify.ID(), data))
![image](https://user-images.githubusercontent.com/3284075/179231367-290f4c64-2203-4fed-b1ea-03235f7ab711.png)

something lke this
ID might be useful cuz we need it for deletion

2022-07-15 13:21 UTC, kfedor commented on notifications/inapp/inapp.go
> +func (i *inApp) Get(ctx context.Context, slug, userID string) ([]*NotificationData, error) {
ok

2022-07-15 13:22 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
map[string]string

2022-07-15 13:22 UTC, kfedor commented on notifications/inapp/inapp.go
> +			Header:   resp.Results[c].Verb,
ok

2022-07-15 13:23 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		Actor:  id,
yes,, this is ID() of *Feed(slug,name) which is actually "slug:name" verified

2022-07-15 13:27 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
Parcel struct {
		ID        string // Actor
		Action    string // Verb
		Object    string // Some data
		ForeignID string
		Extra     map[string]string
	}

this ok ?

2022-07-15 13:33 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
```
Parcel struct {
	ReferenceID string
	Action    string // Verb
	Actor      ID
	Subject    ID
	Data   map[string]string
}
ID struct {
   Type string
   Value string
}
```

2022-07-15 13:44 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
oh this is pretty unclear

func (i *inApp) makeActivity(data *Parcel) stream.Activity {
	m := make(map[string]interface{}, len(data.Data))
	for k, v := range data.Data {
		m[k] = v
	}
	return stream.Activity{
		Actor:     fmt.Sprintf("%s:%s", data.Actor.Type, data.Actor.Value),
		Verb:      data.Action,
		ForeignID: data.ReferenceID,
		Object:    fmt.Sprintf("%s:%s", data.Subject.Type, data.Subject.Value),
		Extra:     m,
	}
}

ok?

2022-07-15 13:48 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +	_, err := notify.AddActivity(ctx, i.makeActivity(notify.ID(), data))
ID is server side generated unique id
foreign_id is some common field we can use or no

2022-07-15 14:37 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		Object: "1",
yep

2022-07-15 14:37 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +	_, err := notify.AddActivity(ctx, i.makeActivity(notify.ID(), data))
ok, then yea, we don't care about that id

2022-07-15 14:38 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) SendMulti(ctx context.Context, slug, userID string, data []*NotificationData) error {
I.E. `notifications:userId:1232546`

2022-07-15 18:54 UTC, victor-oancea-leftclick-io requested changes

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +		GetAll(context.Context, string) ([]*Parcel, error)
string what? userId?

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +		Data        map[string]string
does getstream allow map[string]interface{}?

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +		slug   string
feedName

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func New(applicationYamlKey, slug string) Client {
feedName

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +		return &ID{}
put data in value in this case

2022-07-15 18:54 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *inApp) splitID(data string) *ID {
make the receiver on id and rename it to parse, so that it can be used as : new(ID).parse("")

2022-07-16 06:14 UTC, kfedor commented on notifications/inapp/contract.go
> +		GetAll(context.Context, string) ([]*Parcel, error)
ok

2022-07-16 06:31 UTC, kfedor commented on notifications/inapp/contract.go
> +		Data        map[string]string
fixed

2022-07-16 06:31 UTC, kfedor commented on notifications/inapp/inapp.go
> +		return &ID{}
ok

2022-07-16 06:31 UTC, kfedor commented on notifications/inapp/inapp.go
> +func (i *inApp) splitID(data string) *ID {
ok

2022-07-16 10:51 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +func (i *ID) parse(data string) ID {
U dont return a new one, you set i and return it

2022-07-16 10:57 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +func (i *inApp) makeActivity(data *Parcel) stream.Activity {
Move the id.parse method here and the make parcel one

2022-07-16 10:57 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +func (i *inApp) createNotificationFeed(slug, userID string) (*stream.NotificationFeed, error) {
FeedName

2022-07-16 10:58 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +		res = append(res, &Parcel{
Create a reveiver method on parcel with this code

2022-07-16 11:01 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +	cl, err := stream.New(cfg.Credentials.Key, cfg.Credentials.Secret)
Check what i did in eskimo for twilio and do the same thing here:


IN_APP_NOTIFICATIONS_CLIENT_USER
IN_APP_NOTIFICATIONS_CLIENT_PASSWORD

2022-07-18 07:32 UTC, kfedor commented on notifications/inapp/inapp.go
> +	cl, err := stream.New(cfg.Credentials.Key, cfg.Credentials.Secret)
oh, we should do this for all external services

2022-07-18 07:42 UTC, victor-oancea-leftclick-io commented on notifications/inapp/inapp.go
> +	cl, err := stream.New(cfg.Credentials.Key, cfg.Credentials.Secret)
Yep

2022-07-18 10:47 UTC, victor-oancea-leftclick-io commented on server/router.go
> +func RootHandler[T ParsedRequest](r func() T, handleRequest func(context.Context, T) Response) func(*gin.Context) {
how exactly did this happen?

2022-07-18 10:54 UTC, kfedor commented on server/router.go
> +func RootHandler[T ParsedRequest](r func() T, handleRequest func(context.Context, T) Response) func(*gin.Context) {
8-o I just rebased without any conflicts
ill fix

2022-07-18 11:07 UTC, victor-oancea-leftclick-io commented on server/router.go
> +func RootHandler[T ParsedRequest](r func() T, handleRequest func(context.Context, T) Response) func(*gin.Context) {
yea, something is messed up

2022-07-18 11:23 UTC, antonh21 commented on notifications/inapp/contract.go
> +	Parcel struct {
Maybe it worths to add `json` annotations for this structure as it is used for `GetAll` method?

2022-07-18 11:23 UTC, antonh21 commented on notifications/inapp/getstream_feeds.go
> +		i.Type = r[0]
If `data string` is empty, here can be segfault.
```
if len(r) == 1 {
    i.Value = data
} else if len(r) == 2 {
    i.Type = r[0]
    i.Value = r[1]
} else {
    log.Panic(....)
}
```
?

2022-07-18 11:28 UTC, victor-oancea-leftclick-io commented on notifications/inapp/getstream_feeds.go
> +		i.Type = r[0]
nope, its never that, at worst you get an array with 1 element witch is the whole string itself

2022-07-18 11:36 UTC, kfedor commented on notifications/inapp/getstream_feeds.go
> +		i.Type = r[0]
hm if data string is empty we assign "" to i.Value

2022-07-18 11:38 UTC, antonh21 commented on notifications/inapp/contract.go
> +	Parcel struct {
If we call `GetAll` for example from eskimo, we may need to encode the structure to json.

2022-07-18 11:39 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +	Parcel struct {
the parcel has to be json marshallable

2022-07-18 11:40 UTC, kfedor commented on notifications/inapp/contract.go
> +	Parcel struct {
I added but I didnt get the point

2022-07-18 11:44 UTC, victor-oancea-leftclick-io commented on notifications/inapp/contract.go
> +	Parcel struct {
@kfedor most likely we will want to marshall that parcel as a json, either for logging or for sending it to the message broker, so it needs json tags, otherwise everything is serialised as is : {"Data": {}, "UserID": "222"}

That's the point.

2022-07-18 11:45 UTC, antonh21 commented on notifications/inapp/contract.go
> +	Parcel struct {
@kfedor change to camelCase for json annotations please. And add please examples `example:"..."`

2022-07-18 11:45 UTC, victor-oancea-leftclick-io commented on server/router.go
> +func RootHandler[T ParsedRequest](r func() T, handleRequest func(context.Context, T) Response) func(*gin.Context) {
fix this pls

2022-07-18 11:57 UTC, kfedor commented on notifications/inapp/contract.go
> +		UserID      `json:"user_id"`
@victor-oancea-leftclick-io hmm
I used camelCase function instead of snakeCase in IDEA
))

2022-07-18 12:00 UTC, antonh21 commented on notifications/inapp/contract.go
> +		UserID      UserID                 `json:"userId"`
Let's add examples for json annotations like:
```
UserID      UserID                 `json:"userId" example="did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2"`
```

2022-07-18 12:17 UTC, kfedor commented on notifications/inapp/contract.go
> +		UserID      UserID                 `json:"userId"`
ok

2022-07-18 12:21 UTC, victor-oancea-leftclick-io approved these changes

2022-07-18 12:25 UTC, antonh21 approved these changes

2022-07-18 12:32 UTC, merged