email testing fixture
ice-blockchain/wintr pull request #20
Opened 2022-08-19 12:56 UTC by ice-cronus

Function to read validation code from delivered email
Generator of email addresses using https://www.1secmail.com/

2022-08-19 14:12 UTC, ice-cronus commented on email/fixture/fixture.go
> +	for ctx.Err() == nil && len(messageListData) == 0 {
I used the same in the awaiting sms delivery loop in eskimo's fixture, and it died properly when timeout expired (with deadline exceeded), I will recheck.

2022-08-19 14:15 UTC, ice-myles commented on email/fixture/fixture.go
> +	for ctx.Err() == nil && len(messageListData) == 0 {
Okay, nice if so.

2022-08-19 15:00 UTC, ice-myles submitted a review, later dismissed

2022-08-19 16:11 UTC, ice-ares requested changes

2022-08-19 16:11 UTC, ice-ares commented on email/fixture/fixture.go
> +	assert.Len(tb, verificationCode, 6) //nolint:gomnd // 6-digit long code
hell no. remove it, replace it with comparing the actual code and dont return it

2022-08-19 16:11 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
Assert instead of Get, and add the expected code as arg

2022-08-19 16:11 UTC, ice-ares commented on email/fixture/fixture.go
> +	r := regexp.MustCompile(`^<strong>\d+`)
nope, thats implementation specific, provide a func for the user to implement the parsing

2022-08-19 16:11 UTC, ice-ares commented on email/fixture/fixture.go
> +	var messageListData []*struct {
i would extract into separate method: getMailbox

2022-08-19 16:11 UTC, ice-ares commented on email/fixture/fixture.go
> +	var messageInfo struct {
extract into new method: verifyEmailMessage

2022-08-22 07:17 UTC, ice-cronus commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
We still need Get for cmd tests cuz we have no access to database there to get actual code (I removed that strange fixture to find DB connector as we can get code from email now), but we need the code to finish the flow. So I added both functions, that's better than getting DB connector in cmd part.

2022-08-22 12:43 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
U dont need to get it from db, u get it from the body

2022-08-22 12:45 UTC, ice-cronus commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
I mean if we'll have only Assert...(expectedCode string), I'll need to get expected one somewhere, in internal tests I can get it from DB, but for cmd we still need Get..() to get it from the body

2022-08-22 12:50 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string, parseMsg func(msg string) string) string {
U dont need this

2022-08-22 12:51 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
You get it to do what?

2022-08-22 12:52 UTC, ice-cronus commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
to assert the expected one (db's/somewhere's else value) with the actual, from email

2022-08-22 12:53 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string, parseMsg func(msg string) string) string {
Ph, now i get it

2022-08-22 12:53 UTC, ice-cronus commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
And also I need them to confirm an email with correct code

2022-08-22 12:54 UTC, ice-ares commented on email/fixture/fixture.go
> +func GetEmailConfirmationCode(ctx context.Context, tb testing.TB, toEmail string) string {
Nope, u need it to pass it as arg to the validate email endpoint

2022-08-22 12:55 UTC, ice-ares approved these changes

2022-08-22 14:47 UTC, ice-laius approved these changes

2022-08-22 14:53 UTC, merged