Draft: Replace magic.link auth with firebase auth
ice-blockchain/wintr pull request #22
Opened 2022-09-16 06:10 UTC by ice-nestor

In this pr, magic.link authentication is replaced with firebase authentication

2022-09-16 06:12 UTC, ice-nestor commented on server/internal/auth/auth.go
> +	authToken, err := c.client.VerifyIDToken(ctx, token)
Here, we can use a different function for also checking if token was revoked or not, but it will add some overhead. Wdyt ?

@ice-blockchain/golang

2022-09-16 07:05 UTC, ice-ares commented on server/internal/auth/auth.go
> +func New(ctx context.Context, applicationYAMLKey string) (Client, error) {
funcs that are part of the app start flow dont return error, they panic

2022-09-16 07:11 UTC, ice-ares commented on server/server.go
> +func New(state State, authClient auth.Client, cfgKey, swaggerRoot string) Server {
remove the arg, construct it here

2022-09-16 07:13 UTC, ice-ares commented on server/router.go
> +	tokenUserID, err := authClient.VerifyToken(
use all 160 chars horizontal space

2022-09-16 07:14 UTC, ice-ares commented on server/router.go
> +		req.ginCtx.Request.Context(),
this is not the correct ctx, u need ro pass it from line 33

2022-09-16 07:17 UTC, ice-ares commented on server/router.go
> +func RootHandler[REQ any, RESP any](handleRequest func(context.Context, *Request[REQ, RESP]) (*Response[RESP], *Response[ErrorResponse]), authClient auth.Client) func(*gin.Context) {
remove the arg and find another way to pass it

2022-09-16 07:19 UTC, ice-ares commented on server/internal/auth/contract.go
> +var cfg config
u dont need this

2022-09-16 07:19 UTC, ice-ares commented on server/internal/auth/contract.go
> +		} `yaml:"wintr/auth" mapstructure:"wintr/auth"`
wintr/server/auth

2022-09-16 07:20 UTC, ice-ares commented on server/internal/auth/contract.go
> +// Client defines auth service interface
remove comment

2022-09-16 07:20 UTC, ice-ares commented on server/internal/auth/contract.go
> +type UserID = string
group types together

2022-09-16 07:27 UTC, ice-ares commented on server/internal/auth/auth.go
> +	return authToken.UID, nil
return a custom struct named token that contains userId and claims

2022-09-16 07:29 UTC, ice-ares commented on server/internal/auth/auth.go
> +		option.WithCredentialsJSON(
pretty sure thats not gonna work, it needs a json with credentials

2022-09-16 07:30 UTC, ice-ares commented on go.mod
> +	firebase.google.com/go/v4 v4.8.0
i still see magic link sdk is being used, make sure its not

2022-09-16 07:37 UTC, ice-ares commented on server/internal/auth/auth.go
> +	// we can also check if token was revoked ??
yep, use the one with check revoke

2022-09-16 07:38 UTC, ice-ares requested changes
u also have to provide a fixture for that package that will help tests do their logic

2022-09-16 07:40 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		option.WithCredentialsJSON(
```
// WithCredentialsJSON returns a ClientOption that authenticates
// API calls with the given service account or refresh token JSON
// credentials.
```
It's written in comment of that function

2022-09-16 08:11 UTC, ice-ares commented on server/internal/auth/auth.go
> +		option.WithCredentialsJSON(
test it, pretty sure its not gonna work

2022-09-16 08:42 UTC, ice-myles requested changes

2022-09-16 08:42 UTC, ice-myles commented on server/internal/auth/contract.go
> +				ProjectID string `yaml:"projectID" mapstructure:"projectID"`
`projectID` is golang naming, for json/yaml `projectId`

2022-09-16 08:42 UTC, ice-myles commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
> When authorizing via a service account, you have two choices for providing the credentials to your application. You can either set the GOOGLE_APPLICATION_CREDENTIALS environment variable, or you can explicitly pass the path to the service account key in code. **The first option is more secure and is strongly recommended**.

I didn't understand why are you using `AUTH_SERVICE_ACCOUNT`, not `GOOGLE_APPLICATION_CREDENTIALS`? Here are the [recommendations](https://firebase.google.com/docs/admin/setup?hl=en#initialize-sdk).

2022-09-16 08:48 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
I was thinking about how much it's obvious for the user of this function/package that `GOOGLE_APPLICATION_CREDENTIALS` needs to be set without looking into firebase function implementation or reading that above recommendations. Imo, we either keep our own env variable and set it through `option.WithCredentialsJSON` or add comment to `New` function that `GOOGLE_APPLICATION_CREDENTIALS` has to be set before using this function. Wdyt ?

2022-09-16 08:52 UTC, ice-ares commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
Then u dont need any custom cfg at all

2022-09-16 08:57 UTC, ice-ares commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
Actually, you do. You need to specify the custom path to that json

2022-09-16 08:58 UTC, ice-ares commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
Follow the same pattern as with other packages, IE email

2022-09-16 12:18 UTC, ice-nestor commented on server/router.go
> +func RootHandler[REQ any, RESP any](handleRequest func(context.Context, *Request[REQ, RESP]) (*Response[RESP], *Response[ErrorResponse]), authClient auth.Client) func(*gin.Context) {
I can think of 3 different ways to pass auth client, namely:

using a global variable
passing it through standard or gin context
injecting it inside Request structure

All of above 3 methods have downsides for sure, do you have any other ways we could go with ?

@ice-ares

2022-09-16 12:40 UTC, ice-ares commented on server/router.go
> +func RootHandler[REQ any, RESP any](handleRequest func(context.Context, *Request[REQ, RESP]) (*Response[RESP], *Response[ErrorResponse]), authClient auth.Client) func(*gin.Context) {
nope, go with this:
> passing it through standard or gin context

2022-09-16 15:12 UTC, ice-nestor commented on server/internal/auth/contract.go
> +				ServiceAccount string `yaml:"serviceAccount" mapstructure:"serviceAccount"`
afaik if you don't specify this tag, then it uses reflection to guess which field relates to which one, same as it's optional to specify `json` struct tags

2022-09-16 15:13 UTC, ice-nestor commented on server/internal/auth/contract.go
> +				ServiceAccount string `yaml:"serviceAccount" mapstructure:"serviceAccount"`
do you think some field/fields don't require this struct tags ?

2022-09-16 15:23 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		option.WithCredentialsJSON(
tested locally, didn't face any problems

<img width="557" alt="Screen Shot 2022-09-16 at 6 22 01 PM" src="https://user-images.githubusercontent.com/112941283/190674289-9671e49d-af0e-43e4-9883-61acc8fb8a8d.png">
![Screen Shot 2022-09-16 at 6 22 17 PM](https://user-images.githubusercontent.com/112941283/190674318-1a761a8d-20e6-445b-b268-653c1f427f66.png)

2022-09-16 15:23 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		option.WithCredentialsJSON(
![Screen Shot 2022-09-16 at 6 22 17 PM](https://user-images.githubusercontent.com/112941283/190674498-fe90e173-36a0-4086-ae39-9549c46b2948.png)

2022-09-16 18:12 UTC, ice-nestor commented on server/server.go
> +func New(state State, authClient auth.Client, cfgKey, swaggerRoot string) Server {
done

2022-09-16 18:13 UTC, ice-nestor commented on server/router.go
> +	tokenUserID, err := authClient.VerifyToken(
it was 178 actually, had to split it anyhow

2022-09-16 18:13 UTC, ice-nestor commented on server/router.go
> +		req.ginCtx.Request.Context(),
done

2022-09-16 18:13 UTC, ice-nestor commented on server/router.go
> +func RootHandler[REQ any, RESP any](handleRequest func(context.Context, *Request[REQ, RESP]) (*Response[RESP], *Response[ErrorResponse]), authClient auth.Client) func(*gin.Context) {
done

2022-09-16 18:14 UTC, ice-nestor commented on go.mod
> +	firebase.google.com/go/v4 v4.8.0
removed

2022-09-16 18:14 UTC, ice-nestor commented on server/internal/auth/auth.go
> +	// we can also check if token was revoked ??
done

2022-09-16 18:14 UTC, ice-nestor commented on server/internal/auth/auth.go
> +	appCfg "github.com/ice-blockchain/wintr/config"
done

2022-09-16 18:15 UTC, ice-nestor commented on server/internal/auth/contract.go
> +				ProjectID string `yaml:"projectID" mapstructure:"projectID"`
done

2022-09-16 18:20 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
Line 31 is same as `You can either set the GOOGLE_APPLICATION_CREDENTIALS environment variable`, no difference

2022-09-17 13:08 UTC, ice-nestor commented on server/server.go
> +	authClient := auth.New(context.Background(), cfgKey)
We can also get context from the consumer of this package/function

2022-09-19 16:22 UTC, ice-myles commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
> or you can explicitly pass the path to the service account key in code. **The first option is more secure and is strongly recommended**.

2022-09-19 16:26 UTC, ice-nestor commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
We should also consider `However, to sign custom tokens with the specified service account, the Firebase Admin SDK must invoke a remote service.` it's an extra rpc call (same as VerifyIdTokenAndCheckRevoked)

2022-09-19 18:55 UTC, ice-myles requested changes

2022-09-19 18:55 UTC, ice-myles commented on server/internal/auth/auth.go
> +		cfg.WintrAuth.Credentials.ServiceAccount = os.Getenv("AUTH_SERVICE_ACCOUNT")
But [this](https://firebase.google.com/docs/auth/admin/create-custom-tokens?hl=en#using_a_service_account_id) info is about **service account ID** and `GOOGLE_APPLICATION_CREDENTIALS` should contain **service account key**. Are they the same?

2022-09-19 18:55 UTC, ice-myles commented on server/server.go
> +		c.Next()
According [this example in the gin framework doc](https://gin-gonic.com/zh-cn/blog/2019/02/26/how-to-build-one-effective-middleware/) I don't see the sense of `c.Next()` usage here.

2022-09-19 18:55 UTC, ice-myles commented on server/internal/auth/contract.go
> +				ServiceAccount string `yaml:"serviceAccount" mapstructure:"serviceAccount"`
Yep. According to the [mapstructure documentation](https://pkg.go.dev/github.com/mitchellh/mapstructure) `mapstructure` tag is used for 4 cases, but here theoretically can be accepted only 2:
- if you want [to rename field](https://pkg.go.dev/github.com/mitchellh/mapstructure#hdr-Renaming_Fields)
- for [embedded Structs and Squashing](https://pkg.go.dev/github.com/mitchellh/mapstructure#hdr-Embedded_Structs_and_Squashing)

Here you didn't rename any field and also you didn't squash any structure.

2022-09-19 20:54 UTC, ice-myles commented
@ice-nestor please enable auto-merge and make rebase with master.

2022-09-21 05:19 UTC, ice-nestor commented on server/server.go
> +		c.Next()
if we don't use `c.Next()`, how next middleware in chain will be called ?

2022-09-21 05:27 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +		IDToken string `json:"idToken"`
it's a response from firebase, they choose name for json fields :)

so it's `idToken`

2022-09-21 06:03 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +package auth_test
done

2022-09-21 06:15 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	randSource     = rand.New(rand.NewSource(time.Now().UnixNano())) //nolint:gosec // math/rand is okay for benchmarks
done

2022-09-21 06:15 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	ctx := context.Background()
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +//nolint:gochecknoglobals,wrapcheck // it's a benchmark file, so globals and error wraps are okay
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +func getIDToken(ctx context.Context) (string, error) { //nolint:funlen // it's a benchmark function
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	// Create custom user and tokens for testing.
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	user.Email(fmt.Sprintf("%s@%s.com", randomString(10, charsetLetters), randomString(9, charsetLetters)))
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	uid := fmt.Sprintf("%d", rand.NewSource(time.Now().UnixNano()).Int63())
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +func signInWithCustomToken(token string) (string, error) {
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +func randomString(length int, charset string) string {
done

2022-09-21 06:16 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	return idToken, nil
done

2022-09-22 06:30 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	if os.Getenv("GOOGLE_APPLICATION_CREDENTIALS") == "" || os.Getenv("AUTH_API_KEY") == "" {
unfortunately no

2022-09-22 06:38 UTC, ice-nestor commented on server/router.go
> +var errFailedToGetAuthClient = errors.New("failed to get auth client from context") //nolint:grouper // clashes with gofumpt
done

2022-09-22 06:38 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +		if err := firebaseClient.DeleteUser(context.Background(), uid); err != nil {
done

2022-09-22 06:39 UTC, ice-nestor commented on server/server.go
> +	authClient := auth.New(context.Background())
ye, it's a background context, https://github.com/ice-blockchain/wintr/pull/22#discussion_r973584468

2022-09-22 13:42 UTC, ice-ares commented on server/contract.go
> +var errFailedToGetAuthClient = errors.New("failed to get auth client from context") //nolint:grouper // clashes with gofumpt
nope, just panic

2022-09-22 14:03 UTC, ice-ares commented on server/server.go
> +	authClient := auth.New(context.Background())
nope, not like that, u have a setupServer method

2022-09-22 14:05 UTC, ice-ares commented on server/server.go
> +		c.Next()
nope, not like that, setupServer:

BaseContext: func(_ net.Listener) context.Context {
			return context.WithValue(ctx, authClientCtxValueKey, authClient)
		},

2022-09-22 21:07 UTC, ice-nestor commented on server/contract.go
> +var errFailedToGetAuthClient = errors.New("failed to get auth client from context") //nolint:grouper // clashes with gofumpt
done

2022-09-22 21:08 UTC, ice-nestor commented on server/server.go
> +	authClient := auth.New(context.Background())
thanks, that's better approach

2022-09-22 21:08 UTC, ice-nestor commented on server/server.go
> +		c.Next()
done

2022-09-22 21:19 UTC, ice-ares commented on server/server.go
> +	return &srv{
don't reformat stuff just for the sake of it. Reformat only what you modify.

2022-09-22 21:20 UTC, ice-ares commented on server/router.go
> +		panic("failed to get auth client")
never panic, always log.Panic

2022-09-22 21:21 UTC, ice-ares commented on server/router.go
> +		panic("failed to get auth client")
check the million other examples

2022-09-22 21:21 UTC, ice-nestor commented on server/server.go
> +	return &srv{
sure

2022-09-22 21:21 UTC, ice-nestor commented on server/router.go
> +		panic("failed to get auth client")
thanks, nice to know

2022-09-22 21:21 UTC, ice-ares commented on server/router.go
> +		panic("failed to get auth client")
also, u don't need panic, since it would panic anyway it authClient is nil, just use it without checking anything

2022-09-22 21:23 UTC, ice-nestor commented on server/router.go
> +		panic("failed to get auth client")
correct

2022-09-22 21:27 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +package auth
u don't need any test here, all you need are 2 tests, 1 success with valid token, 1 failure with invalid token.

2022-09-22 21:28 UTC, ice-ares commented on server/internal/auth/auth.go
> +func (c *auth) VerifyToken(ctx context.Context, token string) (*Token, error) {
a *auth

2022-09-22 21:29 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +package auth
which tests are we talking about ? I created this file for benchmarks

2022-09-22 21:31 UTC, ice-nestor commented on server/internal/auth/auth.go
> +func (c *auth) VerifyToken(ctx context.Context, token string) (*Token, error) {
nice catch

2022-09-22 21:32 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +package auth
yea, wipe it clean and add a test main, and those 2 tests. + create a fixture/fixture.go with 1 func to generate/get a valid token

2022-09-23 00:17 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +package auth
@ice-ares 
i need to change internal path to pkg then, because this fixture will be used in eskimo and import of internal package isn't allowed from external modules. Or should I create fixtures in different place ?

Or another solution would be calling server fixture from eskimo, and server fixture will be calling internal/auth fixture

2022-09-23 00:30 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	firebaseClient *firebaseAuth.Client
@ice-ares @ice-myles what do you think about this approach ?

2022-09-23 00:59 UTC, ice-ares commented on server/contract.go
> +	authClientCtxKey string
u dont need this

2022-09-23 01:03 UTC, ice-nestor commented on server/contract.go
> +	authClientCtxKey string
removed

2022-09-23 01:04 UTC, ice-ares commented on server/internal/auth/auth.go
> +	client, err := firebaseApp.Auth(ctx)
eager load it, IE. call verifyTokenRevoked and expect some not found error. See mail/notifications packages

2022-09-23 01:04 UTC, ice-ares commented on server/internal/auth/auth.go
> +	if err != nil {
u dont need the ifs

2022-09-23 01:06 UTC, ice-nestor commented on server/internal/auth/auth.go
> +	if err != nil {
<img width="855" alt="Screen Shot 2022-09-23 at 4 06 24 AM" src="https://user-images.githubusercontent.com/112941283/191875783-8c6541dd-c9cc-4e53-b11d-f2c1d7a32c65.png">

you sure ?

2022-09-23 01:06 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +	if testing.Short() {
we dont need to skip it

2022-09-23 01:10 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	if testing.Short() {
you mean we should return ? or to remove testing.Short block ?

2022-09-23 01:13 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	firebaseClient *firebaseAuth.Client
check the sms package, follow the same pattern

2022-09-23 01:14 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	firebaseAuth "firebase.google.com/go/v4/auth"
use this alias everywhere u import this

2022-09-23 01:14 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +func GetUserIDsAndTokens(ctx context.Context, tb testing.TB) (userIDs, tokens []string) {
not needed

2022-09-23 01:16 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +func CreateRandomUserAndGetUID(ctx context.Context, tb testing.TB) string {
GenerateUser

2022-09-23 01:17 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	return uid
return a func as 2nd arg, to cleanup/delete the user

2022-09-23 01:18 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	assert.NoError(tb, err)
always inline

2022-09-23 01:18 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +func GetIDToken(ctx context.Context, tb testing.TB, uid string) string {
SignIn

2022-09-23 01:19 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
what is this?

2022-09-23 01:36 UTC, ice-ares reviewed
add .testdata in auth folder; add server/internal/auth in github action workflow

2022-09-23 07:41 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +package auth
Oh, right. Move auth folder outside of the internal one

2022-09-23 07:43 UTC, ice-ares commented on server/internal/auth/auth.go
> +	if err != nil {
Yea, check the implementation

2022-09-23 07:44 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
A constant deadline, see other packages

2022-09-23 07:44 UTC, ice-ares commented on server/internal/auth/auth_test.go
> +	if testing.Short() {
Remove the if

2022-09-23 07:51 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
Cant you get it using the service account?

2022-09-23 07:52 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
Also, switch to the sign in with email and password one

2022-09-23 13:45 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
And it's the only way to query Firebase API https://firebase.google.com/docs/reference/rest/auth to get these tokens

2022-09-23 14:18 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
I see, ok

2022-09-23 14:25 UTC, ice-ares commented on server/internal/auth/fixture/fixture.go
> +	apiKey := os.Getenv("AUTH_API_KEY")
use GCP_FIREBASE_AUTH_API_KEY as env key

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +func GetIDToken(ctx context.Context, tb testing.TB, uid string) string {
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	assert.NoError(tb, err)
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	return uid
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +func CreateRandomUserAndGetUID(ctx context.Context, tb testing.TB) string {
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +func GetUserIDsAndTokens(ctx context.Context, tb testing.TB) (userIDs, tokens []string) {
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	firebaseAuth "firebase.google.com/go/v4/auth"
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/auth_test.go
> +	if testing.Short() {
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/auth.go
> +	if err != nil {
done

2022-09-23 14:48 UTC, ice-nestor commented on server/contract.go
> +	authClientCtxKey string
done

2022-09-23 14:48 UTC, ice-nestor commented on server/internal/auth/fixture/fixture.go
> +	firebaseClient *firebaseAuth.Client
done

2022-09-23 14:48 UTC, ice-ares commented on .github/workflows/CICD.yaml
> +        - server/pkg/auth
just server/auth

2022-09-23 14:50 UTC, ice-ares commented on server/pkg/auth/auth.go
> +	return &auth{client: client}
don't forget to eager load it, I.E. call a.client.VerifyIDTokenAndCheckRevoked(ctx, token)

2022-09-23 14:50 UTC, ice-nestor commented on server/pkg/auth/auth.go
> +	return &auth{client: client}
yeah, adding that now

2022-09-23 14:52 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +	User struct {
we don't need this

2022-09-23 14:53 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +		fileContent := os.Getenv("AUTH_CREDENTIALS_FILE_CONTENT")
nope, follow the pattern in sms

2022-09-23 14:54 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +func GenerateUser(ctx context.Context, tb testing.TB) (user User, cleanup func(ctx context.Context)) {
func() is enough, use a timed context inside it

2022-09-23 14:54 UTC, ice-nestor commented on server/pkg/auth/fixture/fixture.go
> +		fileContent := os.Getenv("AUTH_CREDENTIALS_FILE_CONTENT")
in sms we are returning twilio client directly, in auth we return interface

2022-09-23 14:55 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +		tb.Helper()
u sure u need this here?

2022-09-23 14:56 UTC, ice-ares commented on server/pkg/auth/contract.go
> +// SPDX-License-Identifier: BUSL-1.1
remove the pkg folder

2022-09-23 14:58 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +		fileContent := os.Getenv("AUTH_CREDENTIALS_FILE_CONTENT")
its the absolute same thing

2022-09-23 15:06 UTC, ice-ares commented on server/pkg/auth/fixture/fixture.go
> +	User struct {
just did

2022-09-23 15:08 UTC, ice-nestor commented on server/pkg/auth/fixture/fixture.go
> +		fileContent := os.Getenv("AUTH_CREDENTIALS_FILE_CONTENT")
oh, my mistake, you created internal pkg in sms which does this, I assumed fixture is calling New function of sms pkg

2022-09-23 15:33 UTC, ice-nestor commented on .github/workflows/CICD.yaml
> +        - server/pkg/auth
done

2022-09-23 15:34 UTC, ice-nestor commented on server/pkg/auth/auth.go
> +	return &auth{client: client}
done

2022-09-23 15:34 UTC, ice-nestor commented on server/pkg/auth/fixture/fixture.go
> +	User struct {
done

2022-09-23 15:34 UTC, ice-nestor commented on server/pkg/auth/fixture/fixture.go
> +func GenerateUser(ctx context.Context, tb testing.TB) (user User, cleanup func(ctx context.Context)) {
done

2022-09-23 15:34 UTC, ice-nestor commented on server/pkg/auth/fixture/fixture.go
> +		tb.Helper()
checked, makes no difference, removed

2022-09-23 15:34 UTC, ice-nestor commented on server/pkg/auth/contract.go
> +// SPDX-License-Identifier: BUSL-1.1
done

2022-09-26 00:04 UTC, merged