SMS package
ice-blockchain/wintr pull request #8
Opened 2022-06-30 14:31 UTC by kfedor

2022-07-01 13:16 UTC, victor-oancea-leftclick-io requested changes

2022-07-01 13:16 UTC, victor-oancea-leftclick-io commented on sms/contract.go
> +		Send(ctx context.Context, parcel Parcel) error
pls always define methods in interfaces without arguments

2022-07-01 13:16 UTC, victor-oancea-leftclick-io commented on sms/sms.go
> +			return nil
return s.Send

2022-07-01 13:16 UTC, victor-oancea-leftclick-io commented on sms/sms.go
> +	return nil
return errors.wrapf(g.wait

2022-07-01 14:17 UTC, nusanovkornilov-leftclick requested changes

2022-07-01 14:23 UTC, kfedor commented on sms/sms.go
> +		_, err := s.client.Api.CreateMessage(new(openapi.CreateMessageParams).
response info is 
type ApiV2010Message struct {
	// The SID of the Account that created the resource
	AccountSid *string `json:"account_sid,omitempty"`
	// The API version used to process the message
	ApiVersion *string `json:"api_version,omitempty"`
	// The message text
	Body *string `json:"body,omitempty"`
	// The RFC 2822 date and time in GMT that the resource was created
	DateCreated *string `json:"date_created,omitempty"`
	// The RFC 2822 date and time in GMT when the message was sent
	DateSent *string `json:"date_sent,omitempty"`
	// The RFC 2822 date and time in GMT that the resource was last updated
	DateUpdated *string `json:"date_updated,omitempty"`
	// The direction of the message
	Direction *string `json:"direction,omitempty"`
	// The error code associated with the message
	ErrorCode *int `json:"error_code,omitempty"`
	// The description of the error_code
	ErrorMessage *string `json:"error_message,omitempty"`
	// The phone number that initiated the message
	From *string `json:"from,omitempty"`
	// The SID of the Messaging Service used with the message.
	MessagingServiceSid *string `json:"messaging_service_sid,omitempty"`
	// The number of media files associated with the message
	NumMedia *string `json:"num_media,omitempty"`
	// The number of messages used to deliver the message body
	NumSegments *string `json:"num_segments,omitempty"`
	// The amount billed for the message
	Price *string `json:"price,omitempty"`
	// The currency in which price is measured
	PriceUnit *string `json:"price_unit,omitempty"`
	// The unique string that identifies the resource
	Sid *string `json:"sid,omitempty"`
	// The status of the message
	Status *string `json:"status,omitempty"`
	// A list of related resources identified by their relative URIs
	SubresourceUris *map[string]interface{} `json:"subresource_uris,omitempty"`
	// The phone number that received the message
	To *string `json:"to,omitempty"`
	// The URI of the resource, relative to `https://api.twilio.com`
	Uri *string `json:"uri,omitempty"`
}

we check error and its enough :))

2022-07-01 15:46 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-07-01 15:47 UTC, victor-oancea-leftclick-io commented on sms/sms.go
> +	return errors.Wrapf(g.Wait(), "error during sending multiple messages")
Nikolay is right, its a best effort, not a fail fast

2022-07-01 19:18 UTC, kfedor commented on sms/sms.go
> +	return errors.Wrapf(g.Wait(), "error during sending multiple messages")
ok you want to collect all errors and return array of errors?

2022-07-02 10:47 UTC, victor-oancea-leftclick-io commented on sms/sms.go
> +	return errors.Wrapf(g.Wait(), "error during sending multiple messages")
Nope, multierror em

2022-07-03 10:03 UTC, victor-oancea-leftclick-io approved these changes

2022-07-04 06:17 UTC, nusanovkornilov-leftclick submitted a review, later dismissed

2022-07-04 06:36 UTC, antonh21 submitted a review, later dismissed

2022-07-04 07:17 UTC, antonh21 submitted a review, later dismissed

2022-07-04 07:19 UTC, nusanovkornilov-leftclick submitted a review, later dismissed

2022-07-04 07:49 UTC, victor-oancea-leftclick-io commented
@kfedor fix conflicts

2022-07-04 13:28 UTC, merged